-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 15:29:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_lsp_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_lsp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_lsp_db` DEFAULT CHARACTER SET utf8 ;
USE `test_lsp_db` ;

-- -----------------------------------------------------
-- Table `test_lsp_db`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`user_types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_lsp_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`users` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_age` INT NULL,
  `user_type` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  INDEX `user_type_idx` (`user_type` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_type`
    FOREIGN KEY (`user_type`)
    REFERENCES `test_lsp_db`.`user_types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `test_lsp_db`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`books` (
  `book_isbn` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NULL,
  `book_author` VARCHAR(45) NULL,
  `book_price` FLOAT NULL,
  `copies_number` INT NULL,
  PRIMARY KEY (`book_isbn`),
  UNIQUE INDEX `book_isbn_UNIQUE` (`book_isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_lsp_db`.`borrowingRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`borrowingRequest` (
  `br_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `book_isbn` INT NULL,
  `br_date` DATETIME NULL,
  `br_duration_in_days` INT NULL,
  `br_is_accepted` TINYINT NOT NULL DEFAULT 0,
  `borrowingRequestcol` VARCHAR(45) NULL,
  PRIMARY KEY (`br_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `book_id_idx` (`book_isbn` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `test_lsp_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `test_lsp_db`.`books` (`book_isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `test_lsp_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `test_lsp_db`.`all_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`all_admins` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `test_lsp_db`.`all_new_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`all_new_users` (`user_id` INT, `user_name` INT, `user_email` INT, `user_age` INT, `user_type` INT);

-- -----------------------------------------------------
-- Placeholder table for view `test_lsp_db`.`all_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lsp_db`.`all_users` (`user_id` INT, `user_name` INT, `user_email` INT, `user_age` INT, `user_type` INT);

-- -----------------------------------------------------
-- procedure routine1
-- -----------------------------------------------------

DELIMITER $$
USE `test_lsp_db`$$
CREATE PROCEDURE `routine1`(
IN user_name varchar(45)
)
BEGIN
insert into users(`user_name`) 
values(user_name);
END$$

DELIMITER ;

-- -----------------------------------------------------
--  routine2
-- -----------------------------------------------------

DELIMITER $$
USE `test_lsp_db`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `test_lsp_db`.`all_admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_lsp_db`.`all_admins`;
USE `test_lsp_db`;
CREATE  OR REPLACE VIEW `all_admins` AS
    SELECT 
        *
    FROM
        USERS
    WHERE
        user_type = 1;

-- -----------------------------------------------------
-- View `test_lsp_db`.`all_new_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_lsp_db`.`all_new_users`;
USE `test_lsp_db`;
CREATE  OR REPLACE VIEW `all_new_users` AS
    SELECT 
        *
    FROM
        users
    WHERE
        user_type = 3;

-- -----------------------------------------------------
-- View `test_lsp_db`.`all_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_lsp_db`.`all_users`;
USE `test_lsp_db`;
CREATE  OR REPLACE VIEW `all_users` AS
    SELECT 
        *
    FROM
        users
    WHERE
        user_type = 2;
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
